name: Auto-update data.json

on:
  schedule:
    - cron: '*/1 * * * *'
  workflow_dispatch:

permissions:
  contents: write     # ← grant write rights

jobs:
  write_time:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true   # ← make sure push uses the GITHUB_TOKEN

      - name: Write new timestamp to data.json
        run: |
          ts="$(date -u +'%Y-%m-%d %H:%M:%S UTC')"
          echo "{ \"time\": \"${ts}\" }" > data.json

      - name: Commit & push data.json
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data.json
          git commit -m "Auto-update at ${ts}" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}